Added a Parent Edit tab
viper-framework/viper-web pull request #1
Opened 2019-11-18 09:12 UTC by redmed666

2019-12-27 20:55 UTC, redmed666 commented
Hi,

Any news for this?

2020-10-23 20:56 UTC, frennkie requested changes

2020-10-23 20:56 UTC, frennkie commented on web/viperweb/views.py
> +        print("IN FUCKING DELETE PARENT VIEW")
same here

2020-10-23 20:56 UTC, frennkie commented on web/viperweb/views.py
> +        print("IN FUCKING ADD PARENT VIEW")
I guess this is not supposed to be merged, right?

2020-10-23 20:56 UTC, frennkie commented
Can you check the conflicts and remove the f***ing lines.. :-D

2020-12-21 11:11 UTC, botherder commented
Closing this for inactivity.

2020-12-21 11:11 UTC, closed without merging